### ISSUE TITLE
LokiJS adapter

### ISSUE THREAD

**Issue by techfort** [mojo-js/crudlet.js#50]
Cool project! Any chance of a LokiJS adapter or a bit of docs to write my own? Thanks!

**Comment by crcn** [comment]
Yep definitely - shouldn't be tough to implement.

**Comment by crcn** [comment]
Here's the initial version: https://github.com/mojo-js/crudlet-loki - let me know if I'm missing anything

**Comment by techfort** [comment]
By Odin, that was faster than Sleipnir!
Looks great Craig, will go through it tonight and experiment, if anything
doesn't work as it should I'll submit PRs on the project repo so you can
close the issue here.
Thanks a lot!

**Comment by crcn** [comment]
Not quite implemented yet - just the docs are done ;). Will implement later tonight (probably).

**Comment by techfort** [comment]
hey no rush, drop me a line when you had a chance to work on it.

**Comment by crcn** [comment]
done - gonna go ahead and close this issue.
